### ISSUE TITLE
SubscriptionEvent is not creating

### ISSUE THREAD

**Issue by Fardeen2001** [chartmogul/chartmogul-node#105]
ChartMogul.SubscriptionEvent.create()
Property 'SubscriptionEvent' may not exist on type 'typeof import("C:/Users/admin/AppData/Local/Microsoft/TypeScript/5.1/node_modules/@types/chartmogul-node/index")'. Did you mean 'Subscription'?ts(2568)
@whobubble

**Comment by swember** [comment]
Hello @Fardeen2001, thank you for reporting this.
I tried to replicate it on the latest lib version locally and didn't face that issue. Could you please provide more details about your env? Which versions of the library and Node do you use?
