### ISSUE TITLE
SchemaInvalidError has a fake specificity

### ISSUE THREAD

**Issue by alexsloan** [chartmogul/chartmogul-node#26]
When making a call with an incorrectly specified type, eg:
```
await(ChartMogul.CustomAttribute.add(cmConfig, entry.uuid, {
    custom: [
           { type: 'String', value: '560dccca5963a44522dd76fd', key: 'shoelaceId' },
           { type: 'Date', value: '2015-10-02T00:16:10.000Z', key: 'phone' }
    ]
}));
```

A fairly specific error is throw:

```
{ SchemaInvalidError: JSON schema validation hasn't passed. {"code":400,"message":"Parameter \"custom[0][type]\" does not have a valid value","param":"custom[0][type]"}
```

This would appear to imply that the first entry is at fault when actually, the second error is the broken one here.

**Comment by jasonl** [comment]
Hi Alex,

Thanks for this issue as well. We'll have a look into it to see what's going on.

**Comment by bilbof** [comment]
Hi Alex,

Thanks a ton for this! It's a valid error. This looks like an issue with our Import API rather than with the Node.js library, so I've written this up in our internal bug tracker and we'll get someone to fix this.

Cheers!

Internal ref: API-169.
