### ISSUE TITLE
Pagination for Metrics.Customer.subscriptions

### ISSUE THREAD

**Issue by pnavarrc** [chartmogul/chartmogul-node#27]
Hi, I’m writing a script to fetch subscriptions for a particular customer, and I’m using the method [`Metrics.Customer.subscriptions`](https://github.com/chartmogul/chartmogul-node#metrics-api) to do that.

It works well, except that I don’t know how to pass pagination parameters (`per_page` and `page`), since the method doesn’t seem to take an options object (unlike `Customer.all`). Is this a current limitation of the library? Is there a workaround for this? Cheers!

**Comment by pkopac** [comment]
Hi @pnavarrc! I'm sorry nobody got to you in reasonable time, we must have missed the notification.
It indeed seems a limitation of just the Node library, so I've filed a bug and we'll fix that ASAP.

**Comment by pkopac** [comment]
Fix released in 1.0.7
