### ISSUE TITLE
Chartmogul-node depends on deprecated package with known vulnerability

### ISSUE THREAD

**Issue by jsedlacek** [chartmogul/chartmogul-node#78]
The [request](https://github.com/request/request) package you're using in chartmogul-node has been deprecated for more than 3 years.

> As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time.

The package has known vulnerability, with no fix:
https://github.com/advisories/GHSA-p8p7-x288-28g6
https://github.com/request/request/issues/3442

Are you planning to switch to a different HTTP package, such as [axios](https://github.com/axios/axios)?

**Comment by galadim1** [comment]
Hello @jsedlacek Thank you for reporting this issue. We would take a look at it.

**Comment by alexleonov-tactiq** [comment]
> We would take a look at it.

It's been a while, any updates @galadim1 ?

**Comment by galadim1** [comment]
> > We would take a look at it.
> 
> It's been a while, any updates @galadim1 ?

Hi, this is still in our backlog and we will get to it soon.

**Comment by alexleonov-tactiq** [comment]
@galadim1 sorry to be a pain in the back, but how is not resolving a vulnerability for more than 6 months fit into your SOC 2 compliance? :) we'll have to drop this library just because it is consider insecure by any measure...

**Comment by galadim1** [comment]
> @galadim1 sorry to be a pain in the back, but how does not resolving a vulnerability for more than six months fit into your SOC 2 compliance? :) we'll have to drop this library just because it is considered insecure by any measure...

Sorry, it took so long. We have a bigger plan with all ChartMogul client Libraries and the reason for the delay (decision-making). the team in charge has started working on the updates for the node client library and in the coming weeks, we will have an updated version.
