### ISSUE TITLE
Query string not passed after replacing `request` library with `superagent`

### ISSUE THREAD

**Issue by marcinrog** [chartmogul/chartmogul-node#91]
Issue Description:

We have encountered a significant issue after transitioning from the request library to superagent for HTTP requests. Specifically, when attempting to fetch all metrics from your endpoint, the `start-date` query parameter, crucial for this request, is not being passed along, leading to failed requests due to the API's requirement for this parameter.

**Comment by alpdal** [comment]
Thanks to @marcinrog, v3.3.2 is released. closing the issue.
